name: Build Check

on:
  pull_request:
    branches:
      - main
      - milestone/**

concurrency:
  group: build-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'
    - name: Build
      with:
        gradle-encryption-key: ${{ secrets.GradleEncryptionKey }}
        github-user: ${{ github.actor }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      uses: ./.github/actions/build-apk
